schema_version: 1

context:
  name: textcase
  version: "0.4.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textcase-${{ version }}.tar.gz
  sha256: 1900dda7d5fc8cf44c414677b9be8b66b2354d9ff4107934ed577f11c1d1210a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - textcase
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/zobweyt/textcase
  summary: A feature-rich Python text case conversion library.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
