schema_version: 1

context:
  name: textcase
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textcase-${{ version }}.tar.gz
  sha256: 1d0b33c35f9bcb2fdc8696b46a0a15ff193db9a6c5c2d2e79368b0b255ca4757

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - textcase
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/zobweyt/textcase
  summary: A feature-rich Python text case conversion library.
  license: GPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
