schema_version: 1

context:
  name: textcase
  version: "0.4.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textcase-${{ version }}.tar.gz
  sha256: 25d81009e5e2a25a9f8ebc81cab6b366ea272c045f33f698b07883f799b7695a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - textcase
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/zobweyt/textcase
  summary: A feature-rich Python text case conversion library.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
